### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ahuangfeng** [network-analytics/draft-ahuang-netconf-notif-yang#9]
- Add that metadata SHOULD be at the top of the message

**Comment by ahuangfeng** [comment]
- [ ] example of a dynamic subscription (enabling the envelope first)
- [ ] enable-notification-envelope in /sn:subscriptions as a "config false" node.
- [ ] Add normative text stating that the RPC can only be used before the creation of any subscription (regardless of the type) and cannot be modified unless there are not any active subscription streaming data.

**Comment by ahuangfeng** [comment]
- [ ] `Metadata nodes SHOULD be located at the begining of the envelope`
Benoit: what is the envelope?  I search through the doc for a definition and it's not well defined. Since there is a SHOULD in this sentence, this is important.
This issue might be solved in the next iteration though.

**Comment by ahuangfeng** [comment]
- [ ] Sec 3.3.1. It is not a notification, it should be a structure

**Comment by ahuangfeng** [comment]
- [ ] Option 2 + restart all subscriptions; notif-envelope=True and all dynamic + configured subscriptions are killed.
- [ ] Default value=false, backwards compatibility

**Comment by ahuangfeng** [comment]
Rob's comment:

<   import ietf-notification-sequencing {
<     prefix inotifseq;
<     reference
<       "draft-tgraf-netconf-notif-sequencing-05: YANG Notifications
<       Sequencing";
<   }
 
Here it is still importing ietf-notification-sequencing, but that is not longer required.
